In [3]:
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
import numpy

In [4]:
iris = datasets.load_iris() # Carrega o dataset iris

x = iris.data[:,:2] # Todas as 150 amostras, mas apenas as duas primeiras características
y = iris.target # Classificação

x_treino = numpy.concatenate( [ x[0:40, :], x[50:90, :], x[100:140, :] ] )
x_teste = numpy.concatenate( [ x[40:50, :], x[90:100, :], x[140:150, :] ] )

y_treino = numpy.concatenate( [ y[0:40], y[50:90], y[100:140] ] )
y_teste = numpy.concatenate( [ y[40:50], y[90:100], y[140:150] ] )


In [6]:
clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(x_treino, y_treino) 

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)

[0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 2 2 1 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [8]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf.fit(x_treino, y_treino)

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)

[0 1 0 0 0 0 0 0 0 0 1 2 1 1 2 1 1 2 2 1 1 1 1 2 2 1 1 2 2 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors = 1)
clf.fit(x_treino, y_treino)

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)