<center><h1>Comparação entre três classificadores</h1></center>
<p>Instituto Federal do Norte de Minas - IFNMG Montes Claros</p>
<p><b>Curso:</b> Ciência da Computação</p>
<p><b>Disciplina:</b> Tópicos em Inteligência Computacional</p>
<p><b>Professora:</b> Luciana Balieiro Cosme</p>
<p><b>Equipe:</b> Yoskoslowich S. N. Fernandes, Breno P. Santos e Daniel</p>

Este trabalho apresenta uma comparação entre três classificadores: MPLClassifier (perceptron multi-camda), KNN e Naive Bayes. A célula abaixo realiza a importanção dos três algoritmos, da base de dados e de outras ferramentas necessárias.

In [13]:
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn import datasets

import matplotlib.pyplot as plt
import numpy
from sklearn.metrics import classification_report, confusion_matrix  

A base de dados utilizada foi a íris que contém 150 amostras; sendo 50 de cada um de três tipos diferentes de flores: setosa, versicolor, virginica. Cada amostra contém quatro características, que são: (1) comprimento da sépala, (2) largura da sépala, (3) comprimento da pétala e (4) largura da pétala; contudo apenas as duas primeiras foram utilizadas. Das 50 amostras de cada classe de flor, 40 foram usadas para treinamento e as outras 10 para testar o aprendizado.

In [14]:
iris = datasets.load_iris() # Carrega o dataset iris

x = iris.data[:,:2] # Todas as 150 amostras, mas apenas as duas primeiras características
y = iris.target # Classificação

x_treino = numpy.concatenate( [ x[0:40, :], x[50:90, :], x[100:140, :] ] )
x_teste = numpy.concatenate( [ x[40:50, :], x[90:100, :], x[140:150, :] ] )

y_treino = numpy.concatenate( [ y[0:40], y[50:90], y[100:140] ] )
y_teste = numpy.concatenate( [ y[40:50], y[90:100], y[140:150] ] )

Abaixo os resultados do MPLClassifier. Ele classificou corretamente 25 das 30 amostras.

In [15]:
clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(x_treino, y_treino) 

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)

print("\n")
print(confusion_matrix(y_teste,y_previsto))  
print("\n")
print(classification_report(y_teste,y_previsto))

[0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 2 2 1 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


[[ 9  1  0]
 [ 0 10  0]
 [ 0  3  7]]


             precision    recall  f1-score   support

          0       1.00      0.90      0.95        10
          1       0.71      1.00      0.83        10
          2       1.00      0.70      0.82        10

avg / total       0.90      0.87      0.87        30



Abaixo os resultados do obtidos com o Naive Bayes. Ele classificou corretamente 26 das 30 amostras.

In [16]:
clf = GaussianNB()
clf.fit(x_treino, y_treino)

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)

print("\n")
print(confusion_matrix(y_teste,y_previsto))  
print("\n")
print(classification_report(y_teste,y_previsto))

[0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 1 2 2 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


[[ 9  1  0]
 [ 0 10  0]
 [ 0  3  7]]


             precision    recall  f1-score   support

          0       1.00      0.90      0.95        10
          1       0.71      1.00      0.83        10
          2       1.00      0.70      0.82        10

avg / total       0.90      0.87      0.87        30



Abaixo os resultados do KNN. Ele classificou corretamente 23 das 30 amostras.

In [17]:
clf = KNeighborsClassifier()
clf.fit(x_treino, y_treino)

y_previsto = clf.predict(x_teste)

print(y_previsto)
print(y_teste)

print("\n")
print(confusion_matrix(y_teste,y_previsto))  
print("\n")
print(classification_report(y_teste,y_previsto))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 1 1 1 2 1 2 2 1 2 1 1 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


[[10  0  0]
 [ 0  9  1]
 [ 0  6  4]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.60      0.90      0.72        10
          2       0.80      0.40      0.53        10

avg / total       0.80      0.77      0.75        30



A tabela abaixo apresenta o número de acertos de cada algoritmo por categoria de flor.

<table>
    <tr>
        <td>Tipo</td>
        <td>MPLClassifier</td>
        <td>Naive Bayes</td>
        <td>KNN</td>
    </tr>
    <tr>
        <td>setosa</td>
        <td>90%</td>
        <td>90%</td>
        <td>100%</td>
    </tr>
    <tr>
        <td>versicolor</td>
        <td>100%</td>
        <td>100%</td>
        <td>90%</td>
    </tr>
    <tr>
        <td>virginica</td>
        <td>70%</td>
        <td>70%</td>
        <td>40%</td>
    </tr>
</table>