Importa as bibliotecas necessárias

In [25]:
import pandas
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix  

Lê os dados a partir de datasets/numericos.csv

In [26]:
arquivo = pandas.read_csv('datasets/numericos.csv', sep=',')
dados = pandas.DataFrame(arquivo)

In [28]:
#randint(0,9)
#x = dados.loc[2, 2]
c1=randint(2,51)
c2=randint(2,51)
x1 = dados.iloc[:,[1,c1,c2]]


In [29]:
a=0
y=[]
for i in x1.iloc[:,0]:
    if i >= 0 and i<=20:
        y.append(1)
    elif i >20 and i<=40:
        y.append(2)
    elif i > 40 and i<=60:
        y.append(3)
    elif i > 60 and i<=80:
        y.append(4)
    elif i> 80 and i<=100:
         y.append(5)
    a=a+1



In [30]:
x1_treino = x1.iloc[0:398582,1:]
x1_teste = x1.iloc[398583:442867,1:]

y1_treino=y[0:398582]
y1_teste=y[398583:442867]


clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(x1_treino, y1_treino) 

y1_previsto = clf.predict(x1_teste)

print("\n")
print(confusion_matrix(y1_teste,y1_previsto))  
print("\n")
print(classification_report(y1_teste,y1_previsto))





[[    0    30  1788     0     0]
 [    0   205 18481     0     0]
 [    0   142 19432     0     0]
 [    0    23  4070     0     0]
 [    0     2   111     0     0]]


             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1818
          2       0.51      0.01      0.02     18686
          3       0.44      0.99      0.61     19574
          4       0.00      0.00      0.00      4093
          5       0.00      0.00      0.00       113

avg / total       0.41      0.44      0.28     44284



In [34]:

with open('output.txt', 'a') as f:    
    print >>f,'Variaveis'+'1'+'\n'
    print >> f, c1,c2+'\n'
    print >>f,'Matriz de confusão'+'1'+'\n'
    print  >>f,confusion_matrix(y1_teste,y1_previsto)
    print >>f,'resulatdo classificação'+'1'+'\n'
    print  >>f,classification_report(y1_teste,y1_previsto)


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [24]:
x1.columns

Index([u'NT_GER', u'CO_CATEGAD', u'QE_I53'], dtype='object')