Importa as bibliotecas necessárias

In [1]:
import pandas
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix  

Lê os dados a partir de datasets/numericos.csv

In [2]:
arquivo = pandas.read_csv('datasets/numericos.csv', sep=',')
dados = pandas.DataFrame(arquivo)

In [3]:
#randint(0,9)
#x = dados.loc[2, 2]
x1 = dados.iloc[:,[1,randint(2,51),randint(2,51)]]


52.6

In [4]:
a=0
y=[]
for i in x1.iloc[:,0]:
    if i >= 0 and i<=20:
        y.append(1)
    elif i >20 and i<=40:
        y.append(2)
    elif i > 40 and i<=60:
        y.append(3)
    elif i > 60 and i<=80:
        y.append(4)
    elif i> 80 and i<=100:
         y.append(5)
    a=a+1



In [5]:
x1_treino = x1.iloc[0:398582,1:]
x1_teste = x1.iloc[398583:442867,1:]

y1_treino=y[0:398582]
y1_teste=y[398583:442867]


clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(x1_treino, y1_treino) 

y1_previsto = clf.predict(x1_teste)

print("\n")
print(confusion_matrix(y1_teste,y1_previsto))  
print("\n")
print(classification_report(y1_teste,y1_previsto))





[[    0   963   855     0     0]
 [    0  9154  9532     0     0]
 [    0  8726 10848     0     0]
 [    0  1647  2446     0     0]
 [    0    45    68     0     0]]


             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1818
          2       0.45      0.49      0.47     18686
          3       0.46      0.55      0.50     19574
          4       0.00      0.00      0.00      4093
          5       0.00      0.00      0.00       113

avg / total       0.39      0.45      0.42     44284



/home/breno/.local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [6]:
with open('out.txt', 'w') as f:
    print('Filename:', filename, file=f)

NT_GER  CO_CATEGAD  QE_I53
0         52.6           1     3.0
1         63.1           1     6.0
2         33.7           1     4.0
3         58.1           1     6.0
4         46.3           1     4.0
5         64.2           1     4.0
6         41.4           1     4.0
7         48.8           1     5.0
8         52.9           1     4.0
9         62.7           1     4.0
10        51.9           1     5.0
11        58.4           1     2.0
12        77.7           1     4.0
13        37.5           1     4.0
14        66.4           1     2.0
15        71.5           1     6.0
16        57.8           1     2.0
17        62.7           1     5.0
18        75.1           1     6.0
19        50.5           1     5.0
20        46.1           1     6.0
21        44.1           1     6.0
22        47.9           1     3.0
23        55.1           1     4.0
24        73.5           1     5.0
25        60.4           1     5.0
26        62.7           1     4.0
27        49.5           1     1.0
28        44.9           1     5.0
29        27.7           1     6.0
...        ...         ...     ...
442838    43.8           5     1.0
442839    46.9           5     8.0
442840    48.2           5     3.0
442841    49.6           5     2.0
442842    63.2           5     1.0
442843    31.9           5     1.0
442844    71.5           5     7.0
442845    59.6           5     3.0
442846    15.1           5     4.0
442847    44.7           5     1.0
442848    30.8           5     7.0
442849    16.3           5     2.0
442850    66.3           5     2.0
442851    34.9           5     7.0
442852    71.9           5     4.0
442853    56.0           5     5.0
442854    45.9           5     7.0
442855    43.3           5     6.0
442856    68.4           5     1.0
442857    39.3           5     7.0
442858    69.6           5     4.0
442859    53.8           5     2.0
442860    15.2           5     1.0
442861    59.8           5     1.0
442862    42.7           5     6.0
442863    35.6           5     5.0
442864    66.1           5     6.0
442865    70.2           5     6.0
442866    51.9           5     3.0
442867    52.8           5     4.0

[442868 rows x 3 columns]